apiVersion: v1
kind: Service
metadata:
  name: coll-47b6c1ee9d434c66bb445775116fb7d0-srv
spec:
  selector:
    app: coll-47b6c1ee9d434c66bb445775116fb7d0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP